### ISSUE TITLE
triggered

### ISSUE THREAD

**Issue by odysseyofthedeveloper** [LordZEDith/Lords-AIO#1]
Thanks for your amazing work :)

**Comment by LordZEDith** [comment]
I don't think you know what you are saying you are stating things without explaining where the issue is ur just another L#'er in need of trying to appeal his superiority over others plus who are you. I see you clearly have no experience ur self, and plus you have no crediblity because I don't know who you are and plus I checked ur git doesn't seem you code another thing is you didn't tell me where my issue is.,and u made no sense "Try to learn a language completely before you try to code a compound." This makes like zero sense.
Not trying to be rude but hope you understand what I am saying

**Comment by LordZEDith** [comment]
Ur account is 1 day old too IMAO

**Comment by odysseyofthedeveloper** [comment]
i'll fuck you to death motherfucker
